// frontend/src/App.tsx
import './App.css';
import { RegistrationForm } from './components/RegistrationForm';
import { FacilitatorQueue } from './components/FacilitatorQueue';
import { CommunityHub } from './components/CommunityHub';

function App() {
  return (
    <main className="layout">
      <header className="hero">
        <div>
          <p className="eyebrow">Hustle Economy · KwaZulu-Natal</p>
          <h1>Connect hustlers, facilitators, and communities in one marketplace.</h1>
          <p className="muted">
            Register your hustle, get verified by local facilitators, and showcase your products/services inside community hubs.
            This MVP wires up the forms, approval flow, and marketplace browsing that will power the Hustle Economy roadmap.
          </p>
        </div>
      </header>
      <RegistrationForm />
      <FacilitatorQueue />
      <CommunityHub />
    </main>
  );
}

export default App;

// frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { RegistrationFormComponent } from './components/registration-form/registration-form.component';
import { FacilitatorQueueComponent } from './components/facilitator-queue/facilitator-queue.component';
import { CommunityHubComponent } from './components/community-hub/community-hub.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RegistrationFormComponent, FacilitatorQueueComponent, CommunityHubComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {}

<main class="layout">
  <header class="hero">
    <p class="eyebrow">Hustle Economy · KwaZulu-Natal</p>
    <h1>Connect hustlers, facilitators, and communities in one marketplace.</h1>
    <p class="muted">Register your business, get verified, and showcase your offerings inside the community hubs.</p>
  </header>

  <app-registration-form></app-registration-form>
  <app-facilitator-queue></app-facilitator-queue>
  <app-community-hub></app-community-hub>
</main>
